# Generated by Django 6.0.1 on 2026-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captiongeneration',
            name='cta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='captiongeneration',
            name='length',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
