# Generated by Django 6.0.1 on 2026-03-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_captiongeneration_cta_captiongeneration_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captiongeneration',
            name='tone',
            field=models.CharField(choices=[('fun', 'Fun'), ('pro', 'Professionnel'), ('inspire', 'Inspirant'), ('educ', 'Éducatif'), ('story', 'Storytelling')], max_length=50),
        ),
    ]
